version: '3'
services:
  selenium-hub:
    container_name: 'selenium-hub'
    build: ./build/selenium_hub
    ports:
      - 4444:4444

  chrome:
    container_name: 'chrome'
    build: ./build/chrome
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - default
    # links:
    #   - selenium-hub:hub

  python:
    container_name: 'python'
    build: ./build/python
    volumes:
      - ./code/:/root/code/
    working_dir: /root/code/
    command: tail -f /dev/null
    networks:
      - default
    depends_on:
      - selenium-hub
    # links:
    #   - selenium-hub:hub


# use default network
networks:
  default:
    external: false
